name: ci-cd

on: [push,pull_request]

jobs:
  ci:
    #OS Setup
    runs-on: ubuntu-latest

    #Define job steps
    steps:
      - name: Set up python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install Package
        run: poetry install
      - name: Build documentation
        run: poetry run make html --directory docs/
